import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import Header from '@/components/header'
import { ReduxProvider } from '@/app/redux-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>          
          {/* Fixed Header */}
          <ReduxProvider>
          <div className='w-full fixed top-0 z-50 h-16'>
            <Header />
          </div>
          <div>
          <SidebarProvider>
            <div className="flex pt-16 w-full">
              <SignedIn>
                <AppSidebar />
              </SignedIn>
              <main className="w-full max-w-7xl mx-auto px-4 relative">
                <SignedIn>
                  {children}
                </SignedIn>
              </main>
            </div>
          </SidebarProvider> 
          </div>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
